### ISSUE TITLE
Android app crashes immediately on launch

### ISSUE THREAD

**Issue by NanoExplorer** [hypertensiune/Mousedroid#2]
Hello,
    Your project looks intriguing, so I tried to get it running. However, when I launch the apk provided in releases, it immediately crashes. 

Here is the adb logcat output (filtered to only display warnings and above because otherwise I had too much information)
```
05-15 00:18:23.230   657   657 E mple.mousedroid: Not starting debugger since process cannot load the jdwp agent.
05-15 00:18:23.274   657   684 W Adreno-AppProfiles: Could not find QSPM HAL service. Skipping adreno profile processing.
05-15 00:18:23.297   657   657 E AndroidRuntime: FATAL EXCEPTION: main
05-15 00:18:23.297   657   657 E AndroidRuntime: Process: com.example.mousedroid, PID: 657
05-15 00:18:23.297   657   657 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.mousedroid/com.example.mousedroid.MainActivity}: java.lang.SecurityException: Settings key: <bluetooth_name> is only readable to apps with targetSdkVersion lower than or equal to: 31
05-15 00:18:23.297   657   657 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4169)
05-15 00:18:23.297   657   657 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4325)
05-15 00:18:23.297   657   657 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
05-15 00:18:23.297   657   657 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
05-15 00:18:23.297   657   657 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
05-15 00:18:23.297   657   657 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2574)
05-15 00:18:23.297   657   657 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
05-15 00:18:23.297   657   657 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:226)
05-15 00:18:23.297   657   657 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:313)
05-15 00:18:23.297   657   657 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8757)
05-15 00:18:23.297   657   657 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-15 00:18:23.297   657   657 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
05-15 00:18:23.297   657   657 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
05-15 00:18:23.297   657   657 E AndroidRuntime: Caused by: java.lang.SecurityException: Settings key: <bluetooth_name> is only readable to apps with targetSdkVersion lower than or equal to: 31
05-15 00:18:23.297   657   657 E AndroidRuntime: 	at android.provider.Settings$NameValueCache.getStringForUser(Settings.java:3323)
05-15 00:18:23.297   657   657 E AndroidRuntime: 	at android.provider.Settings$Secure.getStringForUser(Settings.java:9400)
05-15 00:18:23.297   657   657 E AndroidRuntime: 	at android.provider.Settings$Secure.getString(Settings.java:9356)
05-15 00:18:23.297   657   657 E AndroidRuntime: 	at com.example.mousedroid.MainActivity.onCreate(MainActivity.kt:32)
05-15 00:18:23.297   657   657 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8591)
05-15 00:18:23.297   657   657 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8570)
05-15 00:18:23.297   657   657 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1384)
05-15 00:18:23.297   657   657 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4150)
05-15 00:18:23.297   657   657 E AndroidRuntime: 	... 12 more
05-15 00:18:23.298  2490  6625 W ContextImpl: Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:1252 com.android.server.am.AppErrors.crashApplicationInner:722 com.android.server.am.AppErrors.crashApplication:598 com.android.server.am.ActivityManagerService.handleApplicationCrashInner:10426 com.android.server.am.ActivityManagerService.handleApplicationCrash:10295 
05-15 00:18:23.298  2490  6625 W ActivityManager: crash : com.example.mousedroid,10344
05-15 00:18:23.298  2490  6625 W ActivityTaskManager:   Force finishing activity com.example.mousedroid/.MainActivity
05-15 00:18:23.298  2490  6625 W WindowManager: Prepare app transition: mNextAppTransitionRequests=[TRANSIT_CLOSE], mNextAppTransitionFlags=TRANSIT_FLAG_KEYGUARD_GOING_AWAY_TO_LAUNCHER_WITH_IN_WINDOW_ANIMATIONS | TRANSIT_FLAG_APP_CRASHED, displayId: 0 Callers=com.android.server.wm.DisplayContent.prepareAppTransition:6493 com.android.server.wm.DisplayContent.requestTransitionAndLegacyPrepare:6509 com.android.server.wm.Task.finishTopCrashedActivityLocked:6795 com.android.server.wm.RootWindowContainer.lambda$finishTopCrashedActivities$19:2688 com.android.server.wm.RootWindowContainer.$r8$lambda$4nB35TzseTo6qyVD9NxDieoJN1Y:0 
05-15 00:18:23.300  2490  6625 W WindowManager: Prepare app transition: mNextAppTransitionRequests=[TRANSIT_CLOSE, TRANSIT_CLOSE], mNextAppTransitionFlags=TRANSIT_FLAG_KEYGUARD_GOING_AWAY_TO_LAUNCHER_WITH_IN_WINDOW_ANIMATIONS | TRANSIT_FLAG_APP_CRASHED, displayId: 0 Callers=com.android.server.wm.DisplayContent.prepareAppTransition:6493 com.android.server.wm.DisplayContent.prepareAppTransition:6484 com.android.server.wm.ActivityRecord.finishIfPossible:4145 com.android.server.wm.ActivityRecord.finishIfPossible:3960 com.android.server.wm.Task.finishTopCrashedActivityLocked:6796 
05-15 00:18:23.310  2490  2655 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver
05-15 00:18:23.310  2490  2655 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver
05-15 00:18:23.313  6565  6565 W DMASA[D]: [a]This app does not allow 3rd-party FC detection: com.example.mousedroid
05-15 00:18:23.327  2490  4284 W WindowManager: Prepare app transition: mNextAppTransitionRequests=[TRANSIT_CLOSE, TRANSIT_CLOSE, TRANSIT_OPEN], mNextAppTransitionFlags=TRANSIT_FLAG_KEYGUARD_GOING_AWAY_TO_LAUNCHER_WITH_IN_WINDOW_ANIMATIONS | TRANSIT_FLAG_APP_CRASHED, displayId: 0 Callers=com.android.server.wm.DisplayContent.prepareAppTransition:6493 com.android.server.wm.DisplayContent.prepareAppTransition:6484 com.android.server.wm.TaskFragment.resumeTopActivity:1583 com.android.server.wm.TaskFragment.resumeTopActivity:1307 com.android.server.wm.Task.resumeTopActivityInnerLocked:6449 
05-15 00:18:23.329  2490  4284 W WindowManager: Execute app transition: mNextAppTransitionRequests=[TRANSIT_CLOSE, TRANSIT_CLOSE, TRANSIT_OPEN], mNextAppTransitionFlags=TRANSIT_FLAG_KEYGUARD_GOING_AWAY_TO_LAUNCHER_WITH_IN_WINDOW_ANIMATIONS | TRANSIT_FLAG_APP_CRASHED, displayId: 0 Callers=com.android.server.wm.RootWindowContainer.executeAppTransitionForAllDisplay:2580 com.android.server.wm.ActivityTaskSupervisor.reportResumedActivityLocked:2285 com.android.server.wm.ActivityRecord.completeResumeLocked:6981 com.android.server.wm.TaskFragment.resumeTopActivity:1743 com.android.server.wm.TaskFragment.resumeTopActivity:1307 
05-15 00:18:23.345  2490  4282 W ActivityTaskManager: Request to remove task ignored for non-existent task 7957
05-15 00:18:23.395  2490  4284 W InputManager-JNI: Input channel object 'd780ce4 Splash Screen com.example.mousedroid (client)' was disposed without first being removed with the input manager!
05-15 00:18:23.480  3991  4006 W System  : A resource failed to call release. 
05-15 00:18:23.480  3991  4006 W System  : A resource failed to call release. 
05-15 00:18:23.799  2490  2648 W ActivityTaskManager: Activity top resumed state loss timeout for ActivityRecord{bf4cadd u0 com.example.mousedroid/.MainActivity} t-1 f}}
```

**Comment by hypertensiune** [comment]
Hi, sorry for late response. What android version do you have?

**Comment by NanoExplorer** [comment]
I'm on Android 13

**Comment by hypertensiune** [comment]
So I think I fixed the issue, but it requires bluetooth permission. I couldn't find any other way to get the bluetooth_name in SDK version 31 and higher without that permission
It still works without giving the bluetooth permission but it won't show that name in the server, just the model name which may be ambigous.
